services:
  - type: web
    name: gold-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.headless true --server.enableCORS false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
